remote_theme: daviddarnes/alembic

# 1. Files excluded from Jekyll builds
exclude:
# - README.md
# - CODE_OF_CONDUCT.md
# - CONTRIBUTING.md
# - screenshot.png
# - LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Chat Theatre" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Everything you wanted to know about Chat Theatres" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.ChatTheatre.com" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/ChatTheatre/www.ChatTheatre.com"
email: "Support@ChatTheatre.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# google_analytics: ''
# google_analytics_anonymize_ip: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
